---
variables:
  - &file github-actions/Dockerfile
  - &dhub https://index.docker.io/v1/
  - &repo bksolutions/github_actions
  - &arch linux/amd64

steps:
  prepare:
    when:
      branch: main
    image: alpine/git
    volumes:
      - ${CI_WORKSPACE}:/git
    commands:
      - git clone https://github.com/drone-plugins/github-actions.git

  verify:
    image: alpine
    commands:
      - ls -la
      - mkdir github-actions/cache.build.d
      - mkdir github-actions/cache.mod.d
      - chmod 777 -R github-actions
      - cd github-actions
      - ls -la

  build-go:
    when:
      branch: main
    image: alpinelinux/golang
    commands:
      - whoami
      - id -u $(whoami)
      - export GOOS=linux
      - export GOARCH=amd64
      - export CGO_ENABLED=0
      - export GO111MODULE=on
      - export GOCACHE=${CI_WORKSPACE}/github-actions/cache.build.d
      - export GOMODCACHE=${CI_WORKSPACE}/github-actions/cache.mod.d
      - go build -v -a -tags netgo -o ${CI_WORKSPACE}/github-actions/release/linux/amd64/plugin   ${CI_WORKSPACE}/github-actions/cmd

  build-docker:
    when:
      branch: main
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: *file
      platforms: *arch
      dry_run: true
      repo: *repo
      tags: 
        - 'latest'
      registry: *dhub
      logins:
        - registry: *dhub
          username:
            from_secret: DOCKER_BKSOL_USER
          password:
            from_secret: DOCKER_BKSOL_PASS